name: Build Mission Planner (Debug)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: DEBUG â€“ show root directory
      run: |
        echo "===== ROOT DIRECTORY ====="
        dir
        echo "===== SEARCH MissionPlanner.sln ====="
        dir /s MissionPlanner.sln

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet
      run: nuget restore MissionPlanner.sln -NonInteractive

    - name: Build Release x86
      run: msbuild MissionPlanner.sln /p:Configuration=Release /p:Platform=x86 /m

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: MissionPlanner-Release
        path: MissionPlanner/bin/Release/**
